/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackBtn: typeof import('./src/components/shared/Back-Btn.vue')['default']
    ColorThemePicker: typeof import('./src/components/settings/Color-Theme-Picker.vue')['default']
    ExpansionPanel: typeof import('./src/components/shared/Expansion-Panel.vue')['default']
    FontFamilySettings: typeof import('./src/components/settings/Font-Family-Settings.vue')['default']
    FontSizeSettings: typeof import('./src/components/settings/Font-Size-Settings.vue')['default']
    ImageCard: typeof import('./src/components/shared/Image-Card.vue')['default']
    InitialSoundTask: typeof import('./src/components/tasks/initial_sound/InitialSoundTask.vue')['default']
    ListeningPlaySound: typeof import('./src/components/shared/ListeningPlaySound.vue')['default']
    ListeningTask: typeof import('./src/components/tasks/listening/ListeningTask.vue')['default']
    PhonemesTask: typeof import('./src/components/tasks/phonemes/PhonemesTask.vue')['default']
    PopUpMascotCorrect: typeof import('./src/components/shared/PopUpMascotCorrect.vue')['default']
    PopUpMascotFalse: typeof import('./src/components/shared/PopUpMascotFalse.vue')['default']
    RhymesTask: typeof import('./src/components/tasks/rhymes/RhymesTask.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveCancelButtons: typeof import('./src/components/shared/Save-Cancel-Buttons.vue')['default']
    SelectTask: typeof import('./src/components/main-menu/Select-Task.vue')['default']
    SentenceTask: typeof import('./src/components/tasks/sentences_and_words/SentenceTask.vue')['default']
    SyllableTask: typeof import('./src/components/tasks/syllables/SyllableTask.vue')['default']
    TitleWithSound: typeof import('./src/components/shared/TitleWithSound.vue')['default']
  }
}
