/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackBtn: typeof import('./src/components/shared/Back-Btn.vue')['default']
    ColorThemePicker: typeof import('./src/components/settings/Color-Theme-Picker.vue')['default']
    ExpansionPanel: typeof import('./src/components/shared/Expansion-Panel.vue')['default']
    FontFamilySettings: typeof import('./src/components/settings/Font-Family-Settings.vue')['default']
    FontSizeSettings: typeof import('./src/components/settings/Font-Size-Settings.vue')['default']
    ImageCard: typeof import('./src/components/shared/Image-Card.vue')['default']
    LeftRight: typeof import('./src/components/layouts/left-right.vue')['default']
    ListeningOne: typeof import('./src/components/tasks/listening/Listening-One.vue')['default']
    ListeningPlaySound: typeof import('./src/components/shared/ListeningPlaySound.vue')['default']
    RhymesOne: typeof import('./src/components/tasks/rhymes/Rhymes-One.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveCancelButtons: typeof import('./src/components/shared/Save-Cancel-Buttons.vue')['default']
    SelectTask: typeof import('./src/components/main-menu/Select-Task.vue')['default']
  }
}
